name: Multi-arch Production Build
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ie
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to docker hub
      run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: Build & Push the image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag "${DOCKER_USERNAME}/${IMAGE_NAME}:latest" \
          --push .